import {
  Package,
  Truck,
  Pickaxe,
  HardHat,
  Radar,
  ClipboardCheck,
  Send,
  Cpu,
  Gauge,
  LayoutDashboard,
  Bot,
  Map,
  ChartColumn,
  Navigation,
  CirclePause,
  TriangleAlert,
  MapPin,
  RotateCcwClock,
  Smartphone,
  Route,
  User,
  Clock,
  TrendingUp,
  Fuel,
  FileText,
  Download,
  Megaphone,
  Link as LinkIcon,
  ShieldCheck,
  Funnel,
} from "lucide-react";

export const iconMap = {
  package: Package,
  truck: Truck,
  pickaxe: Pickaxe,
  "hard-hat": HardHat,
  radar: Radar,
  "clipboard-check": ClipboardCheck,
  send: Send,
  cpu: Cpu,
  gauge: Gauge,
  "layout-dashboard": LayoutDashboard,
  bot: Bot,
  map: Map,
  "chart-column": ChartColumn,
  navigation: Navigation,
  "circle-pause": CirclePause,
  "triangle-alert": TriangleAlert,
  "map-pin": MapPin,
  "rotate-ccw-clock": RotateCcwClock,
  smartphone: Smartphone,
  route: Route,
  user: User,
  clock: Clock,
  "trending-up": TrendingUp,
  fuel: Fuel,
  "file-text": FileText,
  download: Download,
  megaphone: Megaphone,
  link: LinkIcon,
  "shield-check": ShieldCheck,
  funnel: Funnel,
};
