import {
  Package,
  Truck,
  Pickaxe,
  HardHat,
  Radar,
  ClipboardCheck,
  Send,
  Cpu,
  Gauge,
  LayoutDashboard,
  Bot,
  Map,
  ChartColumn,
  Navigation,
  CirclePause,
  TriangleAlert,
} from "lucide-react";

export const iconMap = {
  package: Package,
  truck: Truck,
  pickaxe: Pickaxe,
  "hard-hat": HardHat,
  radar: Radar,
  "clipboard-check": ClipboardCheck,
  send: Send,
  cpu: Cpu,
  gauge: Gauge,
  "layout-dashboard": LayoutDashboard,
  bot: Bot,
  map: Map,
  "chart-column": ChartColumn,
  navigation: Navigation,
  "circle-pause": CirclePause,
  "triangle-alert": TriangleAlert,
};
